### ISSUE TITLE
Grunt/Gulp plugin to derive lenses

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-lens#12]
I'm writing up this item to discuss the idea which came up on the hangout last week, specifically creating a Grunt/Gulp plugin which could read a PureScript module, and automatically generate lenses for any data constructors and record types appearing in that module, as a second module, and output it to a file as a part of the build process.

We already have most of the parts we would need for this: the parser and pretty-printer from `purescript-in-purescript` could be extracted into a library (or we could reimplement them), and the interesting part of the code would be a fairly simple traversal of the AST.

**Comment by paf31** [comment]
@joneshf How's this?

https://github.com/paf31/purescript-derive-lenses/

**Comment by kRITZCREEK** [comment]
:+1:

**Comment by joneshf** [comment]
Awesome!
