### ISSUE TITLE
Plated

### ISSUE THREAD

**Issue by puffnfresh** [purescript-contrib/purescript-lens#25]
@ekmett says Plated is very useful for JSON like things and so should be useful in PureScript. It seems like it should be fairly easy to port:

https://hackage.haskell.org/package/lens-3.0.2/docs/Control-Lens-Plated.html

**Comment by paf31** [comment]
:+1:

**Comment by puffnfresh** [comment]
What's the relation between purescript-lens and purescript-optic? Seems like it'd be easier in -optic at the moment since it already has Traversal.

**Comment by joneshf** [comment]
Yeah, it'd be easier to go into `optic` if it depends on `Traversal`. Ideally it'd be nice as a library built on top of whatever you need so `optic` doesn't bloat too much.

Something to be aware of is that the typeclass approach might not work too well at present. You can see this with `At`/`Contains` and friends. The inference doesn't turn out too well. Every so often I'll try and reimplement the `FieldN` family, but usually some bug prevents it from working.

Don't let it deter you though. I say give it a whirl, and see where you get. Might work out great!
