### ISSUE TITLE
Intent to deprecate

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/purescript-lens#40]
We are considering deprecating this library as part of a purescript-contrib cleanup -- see [the full discussion on Discourse](https://discourse.purescript.org/t/proposed-purescript-contrib-library-deprecations) for more details on the effort.

We're considering deprecating purescript-lens because [purescript-profunctor-lenses](https://github.com/purescript-contrib/purescript-profunctor-lenses) has become the de facto way to use lenses in PureScript: it's easier to understand, is actively maintained and expanded, and has documentation resources including a [book](https://leanpub.com/lenses) and [long-form guide](https://thomashoneyman.com/articles/practical-profunctor-lenses-optics/).

This intention follows the proposal from #38 to deprecate in favor of profunctors.

"Deprecation" means that this library either moves to a private maintainer or is moved to the purescript-deprecated organization and made read-only. If the library is deprecated it can still be installed but it won't receive future updates.

Please feel free to weigh in on this discussion either here or in the [Discourse discussion](https://discourse.purescript.org/t/proposed-purescript-contrib-library-deprecations).

**Comment by hdgarrood** [comment]
I think we can go ahead and move this to `purescript-deprecated` since #38 has been open for such a long time and has garnered three thumbs up and no objections.

**Comment by joneshf** [comment]
I ran into this by happenstance, but you should probably ping the maintainer on any of these other deprecation issues.

**Comment by thomashoneyman** [comment]
Good point. I’d assumed a combination of most of them being under my / Gary’s maintenance and the maintainer(s) ideally watching the repository would cover it, but that may not always be the case.
